# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170721_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
