# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170722_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='id',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=140, primary_key=True, serialize=False),
        ),
    ]
