# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170723_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
