# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170721_2031'),
        ('projects', '0002_auto_20170722_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.Skill'),
        ),
    ]
