# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_position_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.Skill'),
        ),
        migrations.AlterField(
            model_name='position',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
    ]
