# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_siteproject_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'vacant'), (1, 'applied'), (2, 'filled')], default=0),
        ),
    ]
